const chatTypes = {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_FAILURE: "FETCH_FAILURE",
    FETCH_ADDITIONAL_START: "FETCH_ADDITIONAL_START",
    ADD_USERS: "ADD_USERS",
    SET_CHAT_USER: "SET_CHAT_USER",
    FETCH_ALL_MESSAGES: "FETCH_ALL_MESSAGES",
    PUSH_MESSAGE_START: "PUSH_MESSAGE_START",
    PUSH_MESSAGE_SUCCESS: "PUSH_MESSAGE_SUCCESS",
    PUSH_MESSAGE_FAILURE: "PUSH_MESSAGE_FAILURE"
}

export default chatTypes;